config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only:[:index, :show, :edit, :update]
  resources :books,only:[:index, :show, :edit, :create, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

   validates :title, presence: true
   validates :body,presence: true,length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name,uniqueness: true,length: { in: 2..20 }
  validates :introduction,length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top,:about]
  before_action :configure_permitted_parameters,if: :devise_controller?

    def after_sign_in_path_for(resource)
      if current_user
        user_path(resource)
      end
    end
  
  add_flash_types :success

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email,:name])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book_new = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
       render :edit
    else
       redirect_to books_path
    end
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
       redirect_to book_path(@book_new), success: "You have created book successfully."
    else
       @books = Book.all
       @user = User.find(current_user.id)
       render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(params[:id]), success: "You have updated book successfully."
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @book_new = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
       render :edit
    else
       redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
       redirect_to user_path(current_user.id), success: "You have updated user successfully."
    else
       render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
<div class="col-md-3">
  <h2>User info</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><%= attachment_image_tag user,:profile_image ,size: '100x100',fallback: "no_image.jpg" %></td>
        </tr>
        <tr>
          <th>name</th>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= user.introduction %></td>
        </tr>
      </tbody>
    </table>

  <div class="row">
    <%= link_to edit_user_path(user.id) ,class: 'btn btn-outline-secondary btn-block' do %>
      <span class="fas fa-user-cog"></span>
    <% end %>
  </div>

  <h2 class="mt-5">New book</h2>
  <%= form_with model: book_new, local: true do |f| %>
  
  <div class="form-group">
      <label>Title</label>
    <%= f.text_field :title ,class: "form-control" %>
  </div>

  <div class="form-group">
      <label>Opinion</label>
      <%= f.text_area :body ,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book" ,class: "form-control btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div class = "alert">
          <%= @book.errors.count %>error prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model: @book,local: true do |f| %>
      <div class="form-group">
        <h5>Title</h5>
        <%= f.text_field :title,class: "form-control" %>
      </div>

      <div class="form-group">
        <h5>Opinion</h5>
        <%= f.text_area :body,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update Book" ,class: "form-control btn btn-success w-25" %>
      </div>
      <% end %>

      <div class="link">
        <%= link_to "Show" ,book_path(@book) %>
       <div class="px-2"> | </div>
        <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book_new.errors.any? %>
  <div class = "alert">
    <%= @book_new.errors.count %>error prohibited this obj from being saved:
      <ul>
        <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'books/userinfo', user: @user ,book_new: @book_new %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <tbody>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% @books.each do |book| %>
      <tr>
        <td><%=link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user,:profile_image,size: "50x50",fallback:"no_image.jpg" %>
            <% end %></td>
        <td><%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'books/userinfo', user: @user ,book_new: @book_new %>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><%= link_to user_path(@book.user_id) do %>
            <%= attachment_image_tag @book.user,:profile_image, size: "50x50",fallback:"no_image.jpg" %></br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to book_path(@book.id) do %>
            <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
          <td><%= link_to "Edit" ,edit_book_path(@book) ,class: 'btn btn-success' %></td>
          <td><%= link_to "Destroy" ,book_path(@book.id), method: :delete,data:{confirm: "本当に消しますか？"} ,class: 'btn btn-danger' %></td>
          <% end %>
        </tr>
      </tbody>
    </table>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="about col-md-6 offset-md-3">welcome to <strong class="fas fa-book">Bookers </strong>!!</h1>
   </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-md-6 offset-md-3">welcome to <strong class="fas fa-book">Bookers </strong>!!</h1>
   </div>

  <div class="row">
    <p class=" message col-md-6 offset-md-3">In<strong class="fas fa-book">Bookers </strong>,</br>
      you can share and exchange your opinions , inpressions , and emotions</br>
      about various books!</p>
  </div>

  <div class="col-md-6 offset-md-3">
    <%= link_to "Log in", new_user_session_path,class: 'btn btn-info btn-block'  %></br>
    <%=link_to "Sign Up", new_user_registration_path,class: 'btn btn-success btn-block' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,intial-scale=1,maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class ="navbar navbar-dark bg-dark">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Bookers</a>
        </div>
      <% if user_signed_in? %>
        <ul class="nav navber-nav">
          <li class="nav-item pr-3"><%= link_to user_path(current_user.id) do %><i class="fas fa-home "> Home</i></li><% end %>
          <li class="nav-item pr-3"><%= link_to users_path do %><i class="fas fa-users"> Users</i></li><% end %>
          <li class="nav-item pr-3"><%= link_to books_path do %><i class="fas fa-book-open"> Books</i></li><% end %>
          <li class="nav-item pr-3"><%= link_to destroy_user_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i> logout</i></li><% end %>
        </ul>
      <% else %>
        <ul class="nav navber-nav">
          <li class="nav-item pr-3"><%= link_to root_path do %><i class="fas fa-home"> Home</i></li><% end %>
          <li class="nav-item pr-3"><%= link_to '/home/about' do %><i class="fas fa-link"> About</i></li><% end %>
          <li class="nav-item pr-3"><%= link_to new_user_registration_path do %><i class="fas fa-user-plus"> sign up</i></li><% end %>
          <li class="nav-item pr-3"><%= link_to new_user_session_path do %><i class="fas fa-sign-in-alt"> login</i></li><% end %>
        </ul>
      </nav>
      <% end %>
    </header>

    <main>
      <div class="container mt-3">
        <% flash.each do |message_type, message| %>
         <div class="alert alert-success"><%= content_tag :div, message, class: message_type %></div>
        <% end %>

        <div class="row">
        <%= yield %>
        </div>
        
      </div>
    </main>

    <footer class="container-mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>User info</h1>
      <% if @user.errors.any? %>
        <div class = "alert">
          <%= @user.errors.count %>error prohibited this obj from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>
          </ul>
        </div>
       <% end %>

      <%= form_with model: @user,local: true do |f| %>
      <div class="form-group">
        <h5>Name</h5>
        <%= f.text_field :name ,class: "form-control" %>
      </div>

      <div class="form-group">
      <h5>Image</h5>
        <%= f.attachment_field :profile_image,class: "form-control-file" , placeholder:"選択されていません"  %>
      </div>

      <div class="form-group">
      <h5>Introduction</h5>
        <%= f.text_area :introduction ,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update User",class: "form-control btn btn-secondary w-25" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
  <%= render 'books/userinfo', user: @user ,book_new: @book_new %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <tbody>
      <tr>
        <th>image</th>
        <th>name</th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user,:profile_image,size: "50x50",format:'jpeg',fallback:"no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show",user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>new</h1>

app/views/users/show.html.erb
<%= render 'books/userinfo', user: @user ,book_new: @book_new %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <tbody>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% @books.each do |book| %>
     <tr>
       <td><%= link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user,:profile_image,size: "50x50",format:'jpeg',fallback:"no_image.jpg" %>
         <% end %>
        </td>
        <td><%= link_to book_path(book.id) do %>
           <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>